# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        run: mvn clean install

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xvisox/notifier-service
          tags: ${{github.run_number}}

      - name: Authenticate with Google Cloud
        if: github.ref == 'refs/heads/master'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Functions
        if: github.ref == 'refs/heads/master'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: 'notifier-service'
          runtime: 'java17'
          entry_point: 'org.springframework.cloud.function.adapter.gcp.GcfJarLauncher'
          source_dir: 'target'
          memory_mb: 512